"""The eight open adversarial scenarios from ROADMAP §5.

The first four in that list — result submitted under another node's id, replay,
expired lease, duplicate after retry — have example-based coverage in
`tests/test_result_binding.py` and are now also generated by
`tests/test_protocol_state_machine.py`. This module is the remaining eight,
each given deliberate, deterministic coverage rather than left to the generator
to stumble into.

Two of them — Sybil registration and colluding verifiers — assert the behaviour
the project *documents*, which is not resistance. Writing a test that asserted
Sybil prevention would assert a guarantee Mycelium does not make.
"""

from __future__ import annotations

import sqlite3
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pytest

import node_capabilities
import server_state as state
import verification
from execution.contracts import ExecutionRequestV1
from execution.validator_protocol import (
    MAX_VALIDATOR_RUNNER_REQUEST_BYTES_V2,
    MAX_VALIDATOR_SCHEMA_BYTES_V2,
    ValidatorContractProjectionV1,
)
from node_enrollments import (
    EnrollmentCredentialConflict,
    EnrollmentLabelConflict,
    EnrollmentRevoked,
    NodeEnrollmentStore,
)
from tests.protocol_harness import (
    ADMISSION_SECRET,
    CREDENTIALS,
    REQUESTER_HOSTS,
    TASK_TEXTS,
    CoordinatorHarness,
)


UNIT_CAP = 2048


@pytest.fixture
def harness(tmp_path):
    coordinator = CoordinatorHarness(Path(tmp_path) / "state")
    try:
        yield coordinator
    finally:
        coordinator.close()


def _open_network(harness: CoordinatorHarness, labels=("n0", "n1")) -> str:
    for index, label in enumerate(labels):
        response = harness.register(label, CREDENTIALS[index], "bootstrap")
        assert response.status_code == 200, response.text
    submission = harness.submit_execution(
        host=REQUESTER_HOSTS[0], task=TASK_TEXTS[0], idempotency_key=None
    )
    assert submission.status_code == 202, submission.text
    return submission.json()["execution_id"]


def _lease(harness: CoordinatorHarness, execution_id: str, task_id: str, *, label: str = "n0",
           lease_seconds: int = 900, cap: int = UNIT_CAP):
    harness.enqueue_unit(
        task_id,
        execution_id=execution_id,
        unit_id=f"candidate-{task_id}",
        max_output_bytes=cap,
        lease_seconds=lease_seconds,
    )
    handout = harness.poll(label)
    assert handout is not None, "the enqueued unit was not handed out"
    return handout


def _credit_and_receipt_agree(harness: CoordinatorHarness) -> None:
    receipts = set(harness.durable_receipts())
    credits = set(harness.durable_credits())
    assert credits == receipts, (
        f"credit/acceptance diverged: only-credited={sorted(credits - receipts)} "
        f"only-accepted={sorted(receipts - credits)}"
    )


# ── 1. Restart mid-submission ────────────────────────────────────────


def test_a_lease_held_across_a_restart_can_never_settle(harness):
    """The queue is process-local, so a restart makes the lease unresumable.

    `docs/PROTOCOL.md` is explicit that the coordinator fails these closed
    rather than accepting a result into a process with no dispatcher waiting.
    """
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0")

    harness.restart()
    harness.register("n0", CREDENTIALS[0], "returning")

    late = harness.submit("u0", harness.result_body(handout), label="n0")
    assert late.status_code == 403, late.text
    assert harness.durable_receipts() == {}
    assert harness.durable_credits() == {}
    assert harness.durable_attempts()[handout.attempt_id]["state"] == "interrupted"


def test_an_accepted_settlement_survives_a_restart_and_replays_exactly(harness):
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0")
    body = harness.result_body(handout)

    accepted = harness.submit("u0", body, label="n0")
    assert accepted.status_code == 200
    first_response = accepted.json()

    harness.restart()
    harness.register("n0", CREDENTIALS[0], "returning")

    replay = harness.submit("u0", body, label="n0")
    assert replay.status_code == 200, replay.text
    assert replay.json() == first_response, "replay after restart changed the response"
    assert len(harness.durable_receipts()) == 1
    assert len(harness.durable_credits()) == 1
    _credit_and_receipt_agree(harness)


@pytest.mark.parametrize("fault_index", list(range(0, 26)))
def test_a_fault_anywhere_in_the_submission_path_leaves_a_truthful_state(tmp_path, fault_index):
    """Sweep the whole result-submission path, one committed statement at a time.

    Whatever the injected disk failure interrupts, the outcome must be one of
    exactly two things: settled with a receipt *and* its credit, or not settled
    at all. There is no third state in which a caller was told something the
    database does not know.
    """
    harness = CoordinatorHarness(Path(tmp_path) / "state")
    try:
        execution_id = _open_network(harness)
        handout = _lease(harness, execution_id, "u0")
        body = harness.result_body(handout)

        harness.faults.arm(target_index=fault_index, mode="io")
        try:
            response = harness.submit("u0", body, label="n0")
            status = response.status_code
        except Exception:
            status = None
        finally:
            harness.faults.disarm()

        receipts = harness.durable_receipts()
        credits = harness.durable_credits()
        assert set(receipts) == set(credits), (
            f"fault at index {fault_index} split settlement from credit"
        )
        assert len(receipts) <= 1

        attempt = harness.durable_attempts()[handout.attempt_id]
        if receipts:
            assert attempt["state"] == "settled"
            if status == 200:
                assert response.json()["status"] == "accepted"
        else:
            assert attempt["state"] != "settled", (
                "an attempt is settled with no durable receipt"
            )

        # And the same answer after a fresh coordinator reads durable state.
        harness.restart()
        assert set(harness.durable_receipts()) == set(receipts)
        assert set(harness.durable_credits()) == set(credits)
    finally:
        harness.close()


def test_a_real_lifespan_restart_agrees_with_the_campaign_restart(tmp_path):
    """The campaign's fast restart must mean the same thing as the real one.

    `CoordinatorHarness.restart()` calls `server_state._init_db()`, which is the
    epoch boundary the FastAPI lifespan calls. This runs the actual lifespan, so
    the shortcut cannot quietly diverge from the thing it stands in for.
    """
    from fastapi.testclient import TestClient

    from server import app

    harness = CoordinatorHarness(Path(tmp_path) / "state")
    try:
        execution_id = _open_network(harness)
        handout = _lease(harness, execution_id, "u0")

        harness.client.__exit__(None, None, None)
        with TestClient(app) as reborn:
            harness.client = reborn
            harness.session_tokens.clear()
            harness.session_ids.clear()
            state.task_queue.clear()
            state.task_inflight.clear()
            harness.register("n0", CREDENTIALS[0], "returning")
            late = harness.submit("u0", harness.result_body(handout), label="n0")
            assert late.status_code == 403, late.text
            assert harness.durable_attempts()[handout.attempt_id]["state"] == "interrupted"
            assert harness.durable_receipts() == {}
    finally:
        harness.close()


def test_an_abandoned_session_has_its_lease_reclaimed_and_its_work_requeued(harness):
    """A laptop closing mid-task is the single most ordinary failure here.

    The worker simply stops talking. After `_NODE_TIMEOUT` the janitor reclaims
    the node, closes its durable attempt, and puts the unit back on the queue —
    and the abandoned worker can never settle it afterwards, even if it wakes up
    holding the original handout.
    """
    execution_id = _open_network(harness, labels=("n0", "n1"))
    handout = _lease(harness, execution_id, "u0", label="n0")
    abandoned_token = harness.session_tokens["n0"]

    harness.clock.advance(state._NODE_TIMEOUT + 30)
    harness.janitor()

    assert "n0" not in state.nodes, "an abandoned node stayed in the registry"
    assert harness.durable_attempts()[handout.attempt_id]["state"] in ("expired", "reclaimed")
    assert [task["task_id"] for task in state.task_queue] == ["u0"], (
        "the abandoned unit was not requeued"
    )

    revived = harness.submit(
        "u0", harness.result_body(handout), label="n0", token=abandoned_token
    )
    assert revived.status_code in (401, 403), revived.text
    assert harness.durable_receipts() == {}
    assert harness.durable_credits() == {}

    # The requeued unit is still workable by somebody else, on a new attempt.
    # The same sweep aged out every node, n1 included, so it reconnects first —
    # which is exactly what the stock worker does after a poll returns 401.
    assert harness.register("n1", CREDENTIALS[1], "returning").status_code == 200
    second = harness.poll("n1")
    assert second is not None and second.attempt_id != handout.attempt_id
    assert harness.submit("u0", harness.result_body(second), label="n1").status_code == 200
    assert len(harness.durable_receipts()) == 1
    _credit_and_receipt_agree(harness)


# ── 2. Clock skew ────────────────────────────────────────────────────


def test_the_worker_protocol_carries_no_timestamp_that_could_move_a_lease():
    """The strongest form of the clock-skew guarantee is structural.

    `TaskResult` and `TokenBatch` have no time field at all except bounded
    `elapsed_seconds`, which is reporting. A worker cannot express a claim about
    when anything happened, so its clock cannot be wrong in a way the
    coordinator would believe.
    """
    for model in (state.TaskResult, state.TokenBatch):
        time_fields = {
            name
            for name in model.model_fields
            if any(token in name for token in ("time", "_at", "clock", "deadline", "expires"))
        }
        assert time_fields == set(), f"{model.__name__} accepts worker-supplied time: {time_fields}"
    assert "elapsed_seconds" in state.TaskResult.model_fields


@pytest.mark.parametrize("elapsed", [0.0, 1.0, 7200.0])
def test_worker_reported_elapsed_time_cannot_extend_an_expired_lease(harness, elapsed):
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0", lease_seconds=30)

    harness.clock.advance(120)  # coordinator time is past the lease
    response = harness.submit(
        "u0", harness.result_body(handout, elapsed_seconds=elapsed), label="n0"
    )

    assert response.status_code == 403, response.text
    assert "lease expired" in response.json()["detail"]
    assert harness.durable_receipts() == {}
    assert harness.durable_credits() == {}


def test_a_backward_coordinator_clock_cannot_revive_a_durably_expired_lease(harness):
    """An NTP correction is not an authority to resurrect settled-away state."""
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0", lease_seconds=30)

    harness.clock.advance(120)
    harness.janitor()
    assert harness.durable_attempts()[handout.attempt_id]["state"] == "expired"

    harness.clock.rewind(600)  # the coordinator's clock jumps back before issue
    # The same forward jump also crossed `_NODE_TIMEOUT`, so the janitor
    # reclaimed the node as stale and its session with it. Re-register, so the
    # submission is refused for the lease rather than for the missing session.
    assert harness.register("n0", CREDENTIALS[0], "returning").status_code == 200
    response = harness.submit("u0", harness.result_body(handout), label="n0")

    assert response.status_code == 403, response.text
    assert harness.durable_receipts() == {}
    assert harness.durable_attempts()[handout.attempt_id]["state"] == "expired"


def test_a_backward_coordinator_clock_does_not_shorten_a_valid_lease(harness):
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0", lease_seconds=900)

    harness.clock.rewind(600)
    response = harness.submit("u0", harness.result_body(handout), label="n0")

    assert response.status_code == 200, response.text
    _credit_and_receipt_agree(harness)


# ── 3. Duplicate identity registration ───────────────────────────────


def test_a_label_or_credential_collision_is_a_stable_conflict(harness):
    _open_network(harness, labels=("n0",))

    same_label = harness.register("n0", CREDENTIALS[5], "bootstrap")
    assert same_label.status_code == 409, same_label.text
    same_credential = harness.register("n2", CREDENTIALS[0], "bootstrap")
    assert same_credential.status_code == 409, same_credential.text

    for response in (same_label, same_credential):
        for credential in CREDENTIALS:
            assert credential not in response.text
    assert len(state.enrollment_store.list()) == 1, "a conflict created a second enrollment"


def test_a_concurrent_bootstrap_race_on_one_label_admits_exactly_one(tmp_path):
    store = NodeEnrollmentStore(Path(tmp_path) / "race.db")
    store.migrate()

    def attempt(index: int):
        try:
            return store.bootstrap("contested", CREDENTIALS[index])
        except (EnrollmentLabelConflict, EnrollmentCredentialConflict) as exc:
            return exc

    with ThreadPoolExecutor(max_workers=6) as pool:
        outcomes = list(pool.map(attempt, range(6)))

    created = [outcome for outcome in outcomes if not isinstance(outcome, Exception)]
    assert len(created) == 1, f"{len(created)} enrollments won one contested label"
    assert store.count() == 1
    assert all(isinstance(other, EnrollmentLabelConflict) for other in outcomes if other not in created)


def test_a_freed_label_does_not_inherit_the_previous_enrollments_history(harness):
    execution_id = _open_network(harness, labels=("n0",))
    handout = _lease(harness, execution_id, "u0")
    assert harness.submit("u0", harness.result_body(handout), label="n0").status_code == 200

    first_enrollment = state.enrollment_store.get_by_node("n0")
    assert first_enrollment is not None
    harness.revoke(first_enrollment.enrollment_id)

    # The label is still owned by the revoked row: it is not recyclable at all,
    # which is a stronger guarantee than "a new enrollment starts empty". The
    # coordinator says *why* — revoked, not merely taken — and either way the
    # freed label cannot be re-enrolled into the old identity's history.
    reuse = harness.register("n0", CREDENTIALS[6], "bootstrap")
    assert reuse.status_code in (403, 409), reuse.text
    assert reuse.json()["detail"]["code"] == "node_enrollment_revoked"
    assert len(state.enrollment_store.list()) == 1, "a revoked label was re-enrolled"

    credits = harness.durable_credits()
    assert len(credits) == 1
    assert next(iter(credits.values()))["enrollment_id"] == first_enrollment.enrollment_id


def test_external_revocation_takes_effect_within_the_documented_delay(harness):
    """An operator revokes with the CLI, which never touches the live process.

    `docs/PROTOCOL.md` documents two enforcement points, and both are asserted
    here: the next authenticated operation observes the revocation, and the
    30-second janitor sweep reclaims an idle session that never makes one.
    """
    execution_id = _open_network(harness, labels=("n0",))
    handout = _lease(harness, execution_id, "u0")
    enrollment = state.enrollment_store.get_by_node("n0")
    assert enrollment is not None

    # Exactly what scripts/node_enrollment_admin.py does: a durable write, with
    # no in-process notification of any kind.
    state.enrollment_store.revoke(enrollment.enrollment_id, "operator revocation")

    refused = harness.submit("u0", harness.result_body(handout), label="n0")
    assert refused.status_code in (401, 403), refused.text
    assert harness.durable_receipts() == {}

    harness.janitor()
    assert harness.durable_attempts()[handout.attempt_id]["state"] != "active", (
        "the janitor sweep left a revoked enrollment holding a live lease"
    )
    assert "n0" not in state.nodes
    assert harness.durable_credits() == {}


def test_one_enrollment_cannot_settle_another_enrollments_attempt(harness):
    """Enrollment isolation, tried from every angle a submitter controls."""
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0", label="n0")
    thief_token = harness.session_tokens["n1"]

    attacks = {
        "claim the victim's label with the thief's session": (
            "n0", thief_token, {}
        ),
        "claim the thief's own label against the victim's attempt": (
            "n1", thief_token, {"node_id": "n1"}
        ),
        "present the victim's label and the victim's own session id as a field": (
            "n1", thief_token, {"node_id": "n1", "execution_id": handout.execution_id}
        ),
    }
    for description, (label, token, overrides) in attacks.items():
        body = harness.result_body(handout, **overrides)
        response = harness.submit("u0", body, label=label, token=token)
        assert response.status_code in (401, 403), f"{description}: {response.text}"
        assert harness.durable_receipts() == {}, description
        assert harness.durable_credits() == {}, description

    # The rightful holder still settles, once.
    assert harness.submit("u0", harness.result_body(handout), label="n0").status_code == 200
    credits = harness.durable_credits()
    assert len(credits) == 1
    victim = state.enrollment_store.get_by_node("n0")
    assert next(iter(credits.values()))["enrollment_id"] == victim.enrollment_id


# ── 4. Oversized and malformed payload ───────────────────────────────


def test_the_canonical_output_limit_is_bounded_at_the_contract():
    for value in (1023, 10_485_761):
        with pytest.raises(ValueError):
            ExecutionRequestV1(task="bounded", max_output_bytes=value)
    assert ExecutionRequestV1(task="bounded", max_output_bytes=1024).max_output_bytes == 1024


def test_an_oversized_result_is_rejected_before_it_can_settle(harness):
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0")

    response = harness.submit(
        "u0",
        harness.result_body(handout, output="x" * (UNIT_CAP + 1)),
        label="n0",
    )

    assert response.status_code == 413, response.text
    body = response.json()
    assert body["max_bytes"] == UNIT_CAP
    assert "x" * 64 not in response.text, "the rejection echoed the payload"
    assert harness.durable_receipts() == {}
    assert harness.durable_credits() == {}
    quarantine = harness.quarantine_rows()
    assert len(quarantine) == 1
    assert len((quarantine[0]["output_preview"] or "").encode("utf-8")) <= 4096


def test_the_error_field_is_bounded_in_characters_and_again_in_bytes(harness):
    """Two different limits, and the inner one is the one that actually binds.

    `TaskResult.error` is capped at 2048 *characters* by the transport model,
    but `AttemptStore.settle` caps it at 2048 *bytes*. A worker sending
    multi-byte text passes the first and must still be refused by the second —
    otherwise the character cap would silently be a 8 KiB byte cap.
    """
    execution_id = _open_network(harness)

    handout = _lease(harness, execution_id, "u0")
    too_many_characters = harness.submit(
        "u0", harness.result_body(handout, output="ok", error="e" * 2049), label="n0"
    )
    assert too_many_characters.status_code == 422, too_many_characters.text
    assert harness.durable_receipts() == {}

    handout = _lease(harness, execution_id, "u1")
    within_characters_over_bytes = "é" * 1500  # 1500 characters, 3000 bytes
    assert len(within_characters_over_bytes) <= 2048
    assert len(within_characters_over_bytes.encode("utf-8")) > 2048
    response = harness.submit(
        "u1",
        harness.result_body(handout, output="ok", error=within_characters_over_bytes),
        label="n0",
    )

    assert response.status_code == 413, response.text
    assert response.json()["field"] == "error"
    assert response.json()["max_bytes"] == 2048
    assert harness.durable_receipts() == {}
    assert harness.durable_credits() == {}


def test_the_streamed_byte_budget_cannot_be_reset_by_reconnecting(harness):
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0", cap=4096)

    accepted = 0
    for _ in range(12):
        response = harness.stream("u0", handout, "t" * 1024)
        if response.status_code == 413:
            break
        assert response.status_code == 200, response.text
        accepted += 1
    else:  # pragma: no cover - the budget must be reachable
        pytest.fail("the cumulative stream budget was never enforced")

    assert accepted * 1024 <= 4096
    # Re-registering is a new incarnation; the durable attempt keeps the budget.
    harness.register("n0", CREDENTIALS[0], "returning")
    assert harness.stream("u0", handout, "t" * 1024).status_code in (403, 409, 413)
    assert harness.durable_receipts() == {}


def test_a_capability_descriptor_beyond_the_protocol_ceiling_is_refused(harness):
    descriptor = harness._descriptor()
    descriptor["limits"]["max_output_bytes"] = node_capabilities.MAX_NODE_OUTPUT_BYTES + 1
    response = harness.client.post(
        "/nodes/register",
        json={
            **harness._registration("n5", CREDENTIALS[7], "bootstrap"),
            "capability_descriptor": descriptor,
        },
        headers={"X-Node-Secret": ADMISSION_SECRET},
    )
    assert response.status_code == 422, response.text
    for credential in CREDENTIALS:
        assert credential not in response.text, "validation echoed the request body"


def test_a_malformed_result_body_is_refused_without_echoing_the_input(harness):
    execution_id = _open_network(harness)
    _lease(harness, execution_id, "u0")

    response = harness.client.post(
        "/tasks/u0/result",
        json={"node_id": "n0", "output": 17, "elapsed_seconds": "soon"},
        headers=harness.headers("n0"),
    )
    assert response.status_code == 422, response.text
    assert "soon" not in response.text, "validation reflected a raw request value"
    assert harness.durable_receipts() == {}


def test_the_validator_runner_control_message_is_bounded():
    """The runner request carries control metadata only, and it is bounded."""
    assert MAX_VALIDATOR_RUNNER_REQUEST_BYTES_V2 == 16 * 1024 * 1024
    with pytest.raises(ValueError):
        ValidatorContractProjectionV1(
            kind="structured_json",
            json_schema={"oversized": "s" * (MAX_VALIDATOR_SCHEMA_BYTES_V2 + 1)},
        )


# ── 5. Sybil registration (documented behaviour, not resistance) ─────


def test_n_bootstraps_under_the_shared_secret_produce_n_independent_enrollments(harness):
    """Mycelium does not claim Sybil resistance, and this asserts what it does claim.

    A holder of `node_secret` can enrol under as many labels as it likes. What
    the protocol guarantees is narrower and still worth having: each identity is
    separately attributed, separately revocable, and earns exactly its own
    credit — one accepted attempt is never worth more than one credit because
    several identities are behind the same operator.
    """
    labels = ("s0", "s1", "s2")
    for index, label in enumerate(labels):
        assert harness.register(label, CREDENTIALS[index], "bootstrap").status_code == 200

    enrollments = {record.node_id: record.enrollment_id for record in state.enrollment_store.list()}
    assert len(set(enrollments.values())) == len(labels), "sybil identities were merged"

    submission = harness.submit_execution(
        host=REQUESTER_HOSTS[0], task=TASK_TEXTS[0], idempotency_key=None
    )
    execution_id = submission.json()["execution_id"]
    for index, label in enumerate(labels):
        handout = _lease(harness, execution_id, f"u{index}", label=label)
        assert harness.submit(f"u{index}", harness.result_body(handout), label=label).status_code == 200

    credits = harness.durable_credits()
    assert len(credits) == len(labels), "one accepted attempt earned more than one credit"
    assert {row["enrollment_id"] for row in credits.values()} == set(enrollments.values())

    # Revocation is per identity: the sybils do not fall together, and they do
    # not shield one another either.
    revoked = enrollments["s1"]
    harness.revoke(revoked)
    assert state.enrollment_store.get(revoked).status == "revoked"
    with pytest.raises(EnrollmentRevoked):
        state.enrollment_store.authenticate("s1", CREDENTIALS[1])
    assert state.enrollment_store.authenticate("s0", CREDENTIALS[0]).status == "active"
    assert len(harness.durable_credits()) == len(labels), "revocation rewrote earned credit"


# ── 6. Colluding verifiers (documented behaviour, not resistance) ────


def test_sampled_agreement_is_off_by_default_and_never_routes():
    """Agreement is a shape observation. It is not correctness and not routing."""
    pool = verification.VerificationPool(verify_rate=0.0)
    assert pool.should_verify(available_nodes=10) is False

    colluding = verification.VerificationPool(verify_rate=1.0)
    for _ in range(20):
        colluding.record_comparison(
            "a", "identical output", "b", "identical output",
            identity_a="enrollment:a", identity_b="enrollment:b",
            enrollment_id_a="a", enrollment_id_b="b",
        )
    record = colluding.agreement_record("enrollment:a")
    assert record.agreement_rate == 1.0

    reported = record.as_dict()
    assert set(reported) == {
        "node_id", "enrollment_id", "sampled_comparisons",
        "agreements", "disagreements", "agreement_rate",
    }
    for forbidden in ("correct", "trust", "score", "rank", "weight", "eligible"):
        assert not any(forbidden in key for key in reported), (
            f"sampled agreement is being reported as {forbidden}"
        )


def test_total_agreement_between_two_nodes_changes_no_placement_decision(harness):
    """Two nodes that always agree with each other gain nothing by it."""
    _open_network(harness)
    descriptor = node_capabilities.NodeCapabilityDescriptorV1.model_validate(
        harness._descriptor()
    )

    def eligibility() -> bool:
        return node_capabilities.match_node_requirements(
            None, [], descriptor, ["code"],
            preferred_model_name="qwen3.5:4b",
            required_output_capacity_bytes=UNIT_CAP,
        ).eligible

    before = eligibility()
    for _ in range(50):
        state.verification_pool.record_comparison(
            "n0", "same shape", "n1", "same shape",
            identity_a="enrollment:n0", identity_b="enrollment:n1",
            enrollment_id_a="n0", enrollment_id_b="n1",
        )
    assert eligibility() == before, "sampled agreement moved an eligibility decision"
    assert state.verification_pool.verify_rate == 0.0
    assert harness.durable_credits() == {}, "agreement created credit"


# ── 7. Disk-full and IO faults ───────────────────────────────────────


@pytest.mark.parametrize("mode", ["io", "commit", "busy"])
def test_a_persistence_failure_during_handout_never_publishes_a_lease(tmp_path, mode):
    """If the attempt is not durable, the worker must not be holding it."""
    harness = CoordinatorHarness(Path(tmp_path) / "state")
    try:
        execution_id = _open_network(harness, labels=("n0",))
        harness.enqueue_unit("u0", execution_id=execution_id, unit_id="candidate-u0")

        harness.faults.arm(target_index=3, mode=mode)
        try:
            response = harness.client.get(
                "/tasks/next", params={"node_id": "n0"}, headers=harness.headers("n0")
            )
        except Exception:
            response = None
        finally:
            harness.faults.disarm()

        durable = harness.durable_attempts()
        if response is not None and response.status_code == 200 and response.json().get("attempt_id"):
            assert response.json()["attempt_id"] in durable, (
                "a lease was handed out that no durable attempt backs"
            )
        else:
            assert durable == {}, "a durable attempt exists that no worker was told about"
    finally:
        harness.close()


def test_a_failed_ledger_projection_cannot_alter_an_accepted_settlement(harness):
    """`ledger.json` is a compatibility projection; SQLite is the authority."""
    execution_id = _open_network(harness)
    handout = _lease(harness, execution_id, "u0")

    # Replace the projection with a directory: `ledger._save` renames a temp
    # file onto this path, which cannot succeed against one.
    projection = harness.root / "ledger.json"
    if projection.exists():
        projection.unlink()
    projection.mkdir(parents=True)

    response = harness.submit("u0", harness.result_body(handout), label="n0")
    assert response.status_code == 200, response.text
    assert response.json()["credits_earned"] == 5
    _credit_and_receipt_agree(harness)
    assert len(harness.durable_credits()) == 1


# ── 8. Crash between verification and settlement ─────────────────────


@pytest.mark.parametrize("fault_index", [0, 1, 2, 3, 4, 5, 6, 7, 8])
def test_a_crash_at_the_settlement_boundary_never_pays_without_accepting(tmp_path, fault_index):
    """Settlement, receipt, and credit are one transaction or none of it.

    A commit-time failure is the sharpest version of "crashed between deciding
    a result is good and recording that decision". Reconcile afterwards and the
    coordinator must still be able to say truthfully which of the two states it
    is in.
    """
    harness = CoordinatorHarness(Path(tmp_path) / "state")
    try:
        execution_id = _open_network(harness, labels=("n0",))
        handout = _lease(harness, execution_id, "u0")

        harness.faults.arm(target_index=fault_index, mode="commit")
        try:
            harness.submit("u0", harness.result_body(handout), label="n0")
        except Exception:
            pass
        finally:
            harness.faults.disarm()

        harness.restart()

        receipts = harness.durable_receipts()
        credits = harness.durable_credits()
        assert set(receipts) == set(credits), (
            f"a commit fault at index {fault_index} paid without accepting, or the reverse"
        )
        attempt = harness.durable_attempts()[handout.attempt_id]
        if receipts:
            assert attempt["state"] == "settled"
        else:
            assert attempt["state"] in ("interrupted", "active", "expired", "cancelled")
            assert attempt["state"] != "settled"

        # Whatever happened, the coordinator's answer is stable on re-reading.
        with sqlite3.connect(harness.database) as con:
            con.row_factory = sqlite3.Row
            settled = con.execute(
                "SELECT COUNT(*) AS n FROM attempts WHERE state = 'settled'"
            ).fetchone()["n"]
        assert settled == len(receipts)
    finally:
        harness.close()
